### ISSUE TITLE
.NET 5

### ISSUE THREAD

**Issue by adamradocz** [chausner/BoincRpc#6]
Could you update the framework to .NET 5? Since .NET 5 the .NET Standard is deprecated.

**Comment by chausner** [comment]
This is what the [official docs](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#when-to-target-net50-vs-netstandard) suggest regarding .NET 5.0 and .NET Standard:
> For existing code that targets netstandard, there's no need to change the TFM to net5.0. .NET 5.0 implements .NET Standard 2.1 and earlier. The only reason to retarget from .NET Standard to .NET 5.0 would be to gain access to more runtime features, language features, or APIs. For example, in order to use C# 9, you need to target .NET 5.0. You can multitarget .NET 5.0 and .NET Standard to get access to newer features and still have your library available to other .NET implementations.

I'd like to keep the library as compatible as possible since not everybody has already moved to .NET 5.0. E.g. I have built a [PowerShell module](https://github.com/chausner/PSBoinc) based on BoincRpc which would no longer run on Windows PowerShell, the version that ships with Windows out-of-the-box.

It seems multi-targeting .NET Standard 2.0 and .NET 5.0 would be an option, theoretically.
